---
apiVersion: t2.stackable.tech/v1
kind: Infra
template: aws-centos-8
metadata: 
  name: monitoring-operator-integration-tests
  description: "Cluster for Monitoring Operator Integration Tests (AWS EC2 / CentOS 8)"
domain: stackable.test
publicKeys: []
spec:
  region: eu-central-1
  wireguard: false
  versions:
    monitoring-operator: "$MONITORING_OPERATOR_VERSION"
  nodes:
    main:
      numberOfNodes: 2
    testdriver:
      numberOfNodes: 1
      agent: false
