---
apiVersion: t2.stackable.tech/v1
kind: Infra
template: aws-centos-8
metadata: 
  name: nifi-operator-integration-tests
  description: "Cluster for NiFi Operator Integration Tests (AWS EC2 / CentOS 8)"
domain: stackable.test
publicKeys: []
spec:
  region: eu-central-1
  k8sVersion: "$K8S_VERSION"
  wireguard: false
  versions:
    nifi-operator: "$NIFI_OPERATOR_VERSION"
  nodes:
    main:
      numberOfNodes: 3
    testdriver:
      numberOfNodes: 1
      k8s_node: false
