[workspace]

members = [
"commons",
# "druid-operator",
# "kafka-operator",
# "monitoring-operator",
# "nifi-operator",
"opa-operator",
"spark-operator",
# "zookeeper-operator",
"hive-operator",
"superset-operator",
# "trino-operator"
]
