[workspace]

members = [
    "airflow-operator",
    "commons",
    #"druid-operator",
    "hive-operator",
    #"kafka-operator",
    # "monitoring-operator",
    # "nifi-operator",
    #"superset-operator",
    "zookeeper-operator"
]
