targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "aarch64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "aarch64-apple-darwin" },
    { triple = "x86_64-apple-darwin" },
]

[advisories]
vulnerability = "warn"
unmaintained = "allow"
unsound = "warn"
yanked = "warn"
notice = "warn"

[bans]
multiple-versions = "allow"

[licenses]
unlicensed = "deny"
copyleft = "deny"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 1.0
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "CC0-1.0",
    "MIT",
    "MPL-2.0",
    "Zlib"
]

[[licenses.clarify]]
name = "encoding_rs"
version = "*"
expression = "(Apache-2.0 OR MIT) AND BSD-3-Clause"
license-files = [
    { path = "COPYRIGHT", hash = 0x39f8ad31 }
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[sources.allow-org]
github = ["stackabletech"]
