---
apiVersion: t2.stackable.tech/v1
kind: Infra
template: aws-centos-8
metadata: 
  name: zookeper-operator-integration-tests
  description: "Cluster for Zookeeper Operator Integration Tests (AWS EC2 / CentOS 8)"
domain: stackable.test
publicKeys: []
spec:
  region: eu-central-1
  wireguard: false
  nodes:
    main:
      numberOfNodes: 3
    testdriver:
      numberOfNodes: 1
      agent: false
