---
apiVersion: t2.stackable.tech/v1
kind: Infra
template: aws-centos-8
metadata: 
  name: opa-operator-integration-tests
  description: "Cluster for Opa Operator Integration Tests (AWS EC2 / CentOS 8)"
domain: stackable.test
publicKeys: []
spec:
  region: eu-central-1
  wireguard: false
  versions:
    opa-operator: "$OPA_OPERATOR_VERSION"
  nodes:
    main:
      numberOfNodes: 3
    testdriver:
      numberOfNodes: 1
      k8s_node: false
