pipeline {
    agent any
    options {
        ansiColor('xterm')
        buildDiscarder(logRotator(numToKeepStr: '5', artifactNumToKeepStr: '5'))
    }

    stages {

        stage('check parameters') {
            when {
                anyOf {
                    expression { env.STACKABLE_OPERATOR == null }
                }
            }
            steps {
                error('Please select an operator using the environment variable STACKABLE_OPERATOR')
            }
        }

        stage('print parameters') {
            when {
                allOf {
                    expression { env.STACKABLE_OPERATOR != null }
                }
            }
            steps {
                echo "Testing the operator: ${env.STACKABLE_OPERATOR}"
            }
        }

        stage('print folder content') {
            steps {
                sh 'cd .ci/'
                sh 'ls -la'
            }
        }

    }
}


