pipeline {
    agent any
    options {
        ansiColor('xterm')
        buildDiscarder(logRotator(numToKeepStr: '5', artifactNumToKeepStr: '5'))
    }

    stages {

        stage('Log variables') {
            steps {
                //sh 'printenv'
                echo "Operator to test: $STACKABLE_OPERATOR"
            }
        }

    }
}
