---
apiVersion: t2.stackable.tech/v1
kind: Infra
template: azure-aks
metadata: 
  name: kafka-operator-integration-tests
  description: "Cluster for Kafka Operator Integration Tests (Azure AKS)"
domain: stackable.test
publicKeys: []
spec:
  versions:
    kafka-operator: "$KAFKA_OPERATOR_VERSION"
  node_count: 3
