---
apiVersion: t2.stackable.tech/v1
kind: Infra
template: hcloud-centos-8
metadata: 
  name: trino-operator-integration-tests
  description: "Cluster for Trino Operator Integration Tests (Hetzner Cloud / CentOS 8)"
domain: stackable.test
publicKeys: []
spec:
  location: "hel1"
  k8sVersion: "$K8S_VERSION"
  wireguard: false
  versions:
    trino-operator: "$TRINO_OPERATOR_VERSION"
    regorule-operator: "RELEASE"
  nodes:
    main:
      numberOfNodes: 3
