---
apiVersion: t2.stackable.tech/v1
kind: Infra
template: ionos-centos-8
metadata: 
  name: zookeper-operator-integration-tests
  description: "Cluster for Zookeeper Operator Integration Tests (IONOS Cloud / CentOS 8)"
domain: stackable.test
publicKeys: []
spec:
  region: de/fra
  k8sVersion: "$K8S_VERSION"
  wireguard: false
  versions:
    zookeeper-operator: "$ZOOKEEPER_OPERATOR_VERSION"
  nodes:
    main:
      numberOfNodes: 3
      numberOfCores: 2
      memoryMb: 4096
      diskType: HDD 
      diskSizeGb: 15
    testdriver:
      numberOfNodes: 1
      numberOfCores: 2
      memoryMb: 4096
      diskType: HDD 
      diskSizeGb: 15
      k8s_node: false
