---
apiVersion: t2.stackable.tech/v1
kind: Infra
template: hcloud-centos-stream-9
metadata: 
  name: superset-operator-integration-tests
  description: "Cluster for Superset Operator Integration Tests (Hetzner Cloud / CentOS 9)"
domain: stackable.test
publicKeys: []
spec:
  location: "hel1"
  k8sVersion: "$K8S_VERSION"
  wireguard: false
  versions:
    _-operator: NIGHTLY
    superset-operator: "$SUPERSET_OPERATOR_VERSION"
  nodes:
    main:
      numberOfNodes: 3
