---
apiVersion: t2.stackable.tech/v1
kind: Infra
template: hcloud-centos-8
metadata: 
  name: monitoring-operator-integration-tests
  description: "Cluster for Monitoring Operator Integration Tests (Hetzner Cloud / CentOS 8)"
domain: stackable.test
publicKeys: []
spec:
  location: "hel1"
  wireguard: false
  versions:
    monitoring-operator: "$MONITORING_OPERATOR_VERSION"
  nodes:
    main:
      numberOfNodes: 2
    testdriver:
      numberOfNodes: 1
      agent: false
