---
apiVersion: t2.stackable.tech/v1
kind: Infra
template: aws-centos-8
metadata: 
  name: druid-operator-integration-tests
  description: "Cluster for Druid Operator Integration Tests (AWS EC2 / CentOS 8)"
domain: stackable.test
publicKeys: []
spec:
  region: eu-central-1
  k8sVersion: "$K8S_VERSION"
  wireguard: false
  versions:
    druid-operator: "$DRUID_OPERATOR_VERSION"
  nodes:
    main:
      numberOfNodes: 3
    testdriver:
      numberOfNodes: 1
      agent: false
