---
name: reviewdog
on:
  pull_request

permissions:
  contents: read
  checks: write
  pull-requests: write
  issues: write

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0
      - uses: reviewdog/action-actionlint@a0541743e79d2ce4ee65276807ac493a93149b7c # tag=v1.23
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0
      - uses: reviewdog/action-detect-secrets@bc7432bf205393ff7453416b3c93853773cee69d # tag=v0.8.1
        with:
          github_token: ${{ secrets.github_token }}

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0
      - uses: actions/setup-python@21c0493ecfd34b1217f0a90ec19a327f3cc0a048 # tag=v3
        with:
          python-version: "3.9"
      - uses: reviewdog/action-flake8@29b3cb2cb65b42f0d6bf5597a5fe6d610f376328 # tag=v3.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  #  Currently disabled due to an issue with running this action on this repo
  #  hadolint:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0
  #      - uses: reviewdog/action-hadolint@2f36e7ddb63420bac655b14287cb6d6b82dd84e2 # tag=v1.28.0
  #        with:
  #          github_token: ${{ secrets.GITHUB_TOKEN }}

  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0
      - uses: reviewdog/action-markdownlint@80ee585e1abc8c910891110289a9abbb52bd35df # tag=v0.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0
      - uses: reviewdog/action-shellcheck@96c6653098ad696d9441d726c0593866671872f2 # tag=v1.14.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0
      - uses: reviewdog/action-yamllint@efeccedfc67c3b74c89e233cd61c8133784b82e0 # tag=v1.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
